import { writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { Flags } from '@oclif/core'
import { BaseCommand } from '../../base-command.js'
import { runDbDiff, isDestructiveSql } from '../../dbdiff.js'
import { DEFAULT_IGNORE_SCHEMAS } from '../../defaults.js'
import { ok, warn, dim, bold, cmd } from '../../ui.js'
import { splitSqlStatements } from '../../utils/sql-split.js'
import { truncateSql } from './run.js'
import { slugify } from '../../utils/strings.js'

/**
 * Generate a new migration file from the current schema drift.
 *
 * Runs a schema diff between source and target, then writes the UP SQL
 * into a timestamped migration file in supabase/migrations/.
 *
 * Replaces `supabase db diff` for self-hosted Supabase instances.
 */
export default class MigrateCreate extends BaseCommand {
  static override description = 'Generate a new migration file from schema drift between environments'

  static override examples = [
    '<%= config.bin %> migrate create --name="add_user_roles"',
    '<%= config.bin %> migrate create --name="update_rls" --source=staging --target=production',
  ]

  static override flags = {
    name: Flags.string({
      char: 'n',
      description: 'Name for the migration (used in filename)',
      required: true,
    }),
    source: Flags.string({ char: 's', description: 'Source environment name' }),
    target: Flags.string({ char: 't', description: 'Target environment name' }),
  }

  async run(): Promise<void> {
    const { flags } = await this.parse(MigrateCreate)

    const config = await this.loadConfigOrFail()
    this.validateDualEnvConfig(config, flags.source, flags.target)

    const sourceEnv = config.environments[config.source!]
    const targetEnv = config.environments[config.target!]
    const dir = this.resolveMigrationsDir(config)
    const ignoreSchemas = config.ignoreSchemas ?? DEFAULT_IGNORE_SCHEMAS

    // Preflight: verify both databases are reachable
    const pre = this.createPreflight('Migrate create preflight checks')
      .addDatabase('Source', config.source!, sourceEnv.dbUrl)
      .addDatabase('Target', config.target!, targetEnv.dbUrl)
    await this.runPreflight(pre, 'Migrate create')

    this.log(`${bold('migrate create')} — diffing ${dim(config.source!)} → ${dim(config.target!)}\n`)

    const result = await runDbDiff({
      sourceUrl: sourceEnv.dbUrl,
      targetUrl: targetEnv.dbUrl,
      type: 'schema',
      include: 'both',
      ignoreSchemas,
    })

    if (!result.up.trim()) {
      this.log(`${ok('No schema drift detected.')} Nothing to write. ✓`)
      return
    }

    // Generate timestamped filename
    const timestamp = generateTimestamp()
    const slug = slugify(flags.name)
    const filename = `${timestamp}_${slug}.sql`

    // Said when the file is written, not first when `migrate run` refuses it:
    // a diff in which the target has a table the source lacks becomes a
    // DROP TABLE here, and the file looks like any other.
    const destructive = splitSqlStatements(result.up).filter(isDestructiveSql)

    // Build file content with UP and optional DOWN
    const lines: string[] = [
      `-- Migration: ${flags.name}`,
      `-- Generated by supaforge migrate create`,
      `-- Source: ${config.source!} → Target: ${config.target!}`,
      ...(destructive.length > 0
        ? [`-- WARNING: ${destructive.length} destructive statement(s) — drops or deletes data. Review before running.`]
        : []),
      '',
      result.up,
    ]

    if (result.down.trim()) {
      lines.push(
        '',
        '-- ==================== DOWN ====================',
        '-- To revert this migration, run the SQL below manually:',
        '--',
        ...result.down.split('\n').map(l => `-- ${l}`),
      )
    }

    const content = lines.join('\n') + '\n'

    // Write file
    await mkdir(dir, { recursive: true })
    const filePath = join(dir, filename)
    await writeFile(filePath, content, 'utf8')

    this.log(`${ok('Created migration:')} ${cmd(filePath)}`)
    if (destructive.length > 0) {
      this.log(`\n${warn(`${destructive.length} destructive statement(s) in it`)} ${dim('— they drop or delete data:')}`)
      for (const sql of destructive) this.log(`  ${warn('✗')} ${dim(truncateSql(sql))}`)
      this.log(`  ${dim('Review them; migrate run applies them only with --allow-destructive.')}`)
    }
    this.log(`\n  ${dim('To preview:')} ${cmd(`supaforge migrate run --env=${config.target!}`)}`)
    this.log(`  ${dim('To apply:')} ${cmd(`supaforge migrate run --env=${config.target!} --apply`)}`)
    this.log(`  ${dim('To baseline:')} ${cmd(`supaforge migrate baseline --env=${config.target!}`)}`)
  }
}

/** Generate a UTC timestamp in Supabase migration format: YYYYMMDDHHmmss */
export function generateTimestamp(): string {
  const now = new Date()
  return [
    now.getUTCFullYear(),
    pad(now.getUTCMonth() + 1),
    pad(now.getUTCDate()),
    pad(now.getUTCHours()),
    pad(now.getUTCMinutes()),
    pad(now.getUTCSeconds()),
  ].join('')
}

function pad(n: number): string {
  return String(n).padStart(2, '0')
}

/** Re-export for backward-compat — uses shared slugify with underscore separator. */
export { slugify } from '../../utils/strings.js'
