/**
 * A snapshot restored into an empty database is the database it was taken
 * from, by pg-conformance's fingerprint — not merely a command that exits 0.
 *
 * The other snapshot tests cover the guard rails: a dry run by default, a
 * refusal to restore over a non-empty database. Nothing restored one and
 * looked at the result, so a release smoke test was the first to notice a
 * restore that lost every policy's comment: the RLS layer drops and recreates
 * each policy after the schema dump had set its comment.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { readdir } from 'node:fs/promises'
import { join } from 'node:path'
import { fingerprintSql } from '@akalforge/pg-conformance'
import { PgHarness } from '../harness/PgHarness.js'
import { describeWithContainers } from '../harness/containers.js'

const describeE2E = describeWithContainers()

/** What a project's schema typically holds, each kind commented. */
const SOURCE = `
  CREATE TYPE state AS ENUM ('new', 'paid');
  CREATE TABLE orders (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner text NOT NULL,
    state state NOT NULL DEFAULT 'new',
    total numeric(12,2) CONSTRAINT orders_total_nonneg CHECK (total >= 0)
  );
  CREATE INDEX orders_owner ON orders (owner);
  CREATE VIEW open_orders AS SELECT id, owner FROM orders WHERE state = 'new';
  CREATE FUNCTION order_count() RETURNS bigint LANGUAGE sql STABLE AS $$ SELECT count(*) FROM orders $$;
  ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
  CREATE POLICY own_orders ON orders USING (owner = current_user);
  COMMENT ON TABLE orders IS 'customer orders';
  COMMENT ON COLUMN orders.total IS 'gross, in pounds';
  COMMENT ON POLICY own_orders ON orders IS 'buyers see their own orders';
  COMMENT ON FUNCTION order_count() IS 'how many orders there are';
  COMMENT ON VIEW open_orders IS 'not yet paid';
  COMMENT ON CONSTRAINT orders_total_nonneg ON orders IS 'no negative totals';
  INSERT INTO orders (owner, total) VALUES ('a', 10), ('b', 20);
`

describeE2E('e2e: snapshot restored into an empty database', () => {
  let h: PgHarness
  let ws: string
  const restored = 'sf_restored'

  beforeAll(async () => {
    h = new PgHarness({ verbose: !!process.env.E2E_VERBOSE, keep: !!process.env.E2E_KEEP })
    await h.up()
    await h.applySql('source', SOURCE)
    await h.createDatabase('target', restored)
    ws = await h.workspace({
      environments: {
        source: { dbUrl: h.connectionString('source') },
        target: { dbUrl: h.connectionString('target') },
        restored: { dbUrl: h.urlFor('target', restored) },
      },
    })
  }, 300_000)

  afterAll(async () => { await h?.down() }, 120_000)

  it('restores the schema exactly, comments included', async () => {
    const snap = await h.cli(['snapshot', '-e', 'source', '--apply'], { cwd: ws })
    expect(snap.code, snap.stdout + snap.stderr).toBe(0)
    const [snapshot] = await readdir(join(ws, '.supaforge', 'snapshots'))

    const restore = await h.cli(['restore', '-e', 'restored', '--from-snapshot', snapshot, '--apply'], { cwd: ws })
    expect(restore.code, restore.stdout + restore.stderr).toBe(0)

    const fingerprint = fingerprintSql(['public']).replace(/;\s*$/, '')
    const source = await h.sql('source', fingerprint)
    const copy = await h.sqlIn('target', restored, fingerprint)
    expect(copy.split('\n')).toEqual(source.split('\n'))
    expect(copy).toContain('cmt policy own_orders on public.orders buyers see their own orders')
  }, 600_000)

  it('then finds no drift between the two', async () => {
    const r = await h.cli(['diff', '--target', 'restored', '--check', 'schema', '--json'], { cwd: ws })
    const scan = JSON.parse(r.stdout) as { checks: Array<{ check: string; issues: unknown[] }> }
    expect(scan.checks.flatMap(c => c.issues), r.stdout).toEqual([])
  }, 300_000)
})
