/**
 * A snapshot restored into an empty database is the database it was taken
 * from, by pg-conformance's fingerprint — not merely a command that exits 0.
 *
 * The other snapshot tests cover the guard rails: a dry run by default, a
 * refusal to restore over a non-empty database. Nothing restored one and
 * looked at the result, so a release smoke test was the first to notice a
 * restore that lost every policy's comment: the RLS layer drops and recreates
 * each policy after the schema dump had set its comment.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { cp, readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fingerprintSql } from '@akal/pg-conformance'
import { PgHarness } from '../harness/PgHarness.js'
import { describeWithContainers } from '../harness/containers.js'

const describeE2E = describeWithContainers()

/** What a project's schema typically holds, each kind commented. */
const SOURCE = `
  CREATE TYPE state AS ENUM ('new', 'paid');
  CREATE TABLE orders (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner text NOT NULL,
    state state NOT NULL DEFAULT 'new',
    total numeric(12,2) CONSTRAINT orders_total_nonneg CHECK (total >= 0)
  );
  CREATE INDEX orders_owner ON orders (owner);
  CREATE VIEW open_orders AS SELECT id, owner FROM orders WHERE state = 'new';
  CREATE FUNCTION order_count() RETURNS bigint LANGUAGE sql STABLE AS $$ SELECT count(*) FROM orders $$;
  ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
  CREATE POLICY own_orders ON orders USING (owner = current_user);
  COMMENT ON TABLE orders IS 'customer orders';
  COMMENT ON COLUMN orders.total IS 'gross, in pounds';
  COMMENT ON POLICY own_orders ON orders IS 'buyers see their own orders';
  COMMENT ON FUNCTION order_count() IS 'how many orders there are';
  COMMENT ON VIEW open_orders IS 'not yet paid';
  COMMENT ON CONSTRAINT orders_total_nonneg ON orders IS 'no negative totals';
  INSERT INTO orders (owner, total) VALUES ('a', 10), ('b', 20);

  -- A schema holding only a domain and a composite type, which introspection
  -- does not list, and one holding nothing yet: both are the project's.
  CREATE SCHEMA billing;
  CREATE DOMAIN billing.amount AS numeric(12,2) CHECK (VALUE >= 0);
  CREATE TYPE billing.address AS (line1 text, postcode text);
  CREATE SCHEMA staging;
  CREATE TABLE invoices (id int PRIMARY KEY, total billing.amount, ship_to billing.address);

  -- Reference data, captured as rows: values JSON numbers or the driver would
  -- lose, an identity and a generated column, and a child listed before its
  -- parent in checks.data.tables.
  CREATE TABLE plans (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code text UNIQUE NOT NULL,
    price numeric(30,10),
    quota bigint,
    since timestamptz,
    badge bytea,
    tags text[],
    raw json,
    doc jsonb,
    doubled numeric GENERATED ALWAYS AS (price * 2) STORED
  );
  CREATE TABLE features (id serial PRIMARY KEY, plan_id bigint NOT NULL REFERENCES plans (id), name text);
  -- json keeps its text exactly — spacing, key order, a duplicate key — and a
  -- JSON null is not an SQL NULL.
  INSERT INTO plans (code, price, quota, since, badge, tags, raw, doc) VALUES
    ('free', 0, 9007199254740993, '2026-01-01 00:00:00.123456+05:30', '\\x00ff10', '{a,"b c"}', '{"dup": 1,  "dup": 2, "b": []}', 'null'),
    ('pro', 12345678901234567890.0123456789, NULL, NULL, NULL, NULL, '[]', NULL);
  INSERT INTO features (plan_id, name) VALUES (1, 'one'), (2, 'two'), (2, 'three');
`

describeE2E('e2e: snapshot restored into an empty database', () => {
  let h: PgHarness
  let ws: string
  const restored = 'sf_restored'

  beforeAll(async () => {
    h = new PgHarness({ verbose: !!process.env.E2E_VERBOSE, keep: !!process.env.E2E_KEEP })
    await h.up()
    await h.applySql('source', SOURCE)
    await h.createDatabase('target', restored)
    ws = await h.workspace({
      environments: {
        source: { dbUrl: h.connectionString('source') },
        target: { dbUrl: h.connectionString('target') },
        restored: { dbUrl: h.urlFor('target', restored) },
        partial: { dbUrl: h.urlFor('target', 'sf_partial') },
        old: { dbUrl: h.urlFor('target', 'sf_old_format') },
        rolledback: { dbUrl: h.urlFor('target', 'sf_rolled_back') },
      },
      checks: { data: { tables: ['public.features', 'public.plans'] } },
    })
  }, 300_000)

  afterAll(async () => { await h?.down() }, 120_000)

  it('restores the schema exactly, comments included', async () => {
    const snap = await h.cli(['snapshot', '-e', 'source', '--apply'], { cwd: ws })
    expect(snap.code, snap.stdout + snap.stderr).toBe(0)
    const [snapshot] = await readdir(join(ws, '.supaforge', 'snapshots'))

    const restore = await h.cli(['restore', '-e', 'restored', '--from-snapshot', snapshot, '--apply'], { cwd: ws })
    expect(restore.code, restore.stdout + restore.stderr).toBe(0)

    const fingerprint = fingerprintSql(['public', 'billing']).replace(/;\s*$/, '')
    const source = await h.sql('source', fingerprint)
    const copy = await h.sqlIn('target', restored, fingerprint)
    expect(copy.split('\n')).toEqual(source.split('\n'))
    expect(copy).toContain('cmt policy own_orders on public.orders buyers see their own orders')

    const schemas = `SELECT string_agg(nspname, ',' ORDER BY nspname) FROM pg_namespace WHERE nspname IN ('billing', 'staging')`
    expect(await h.sqlIn('target', restored, schemas)).toBe('billing,staging')

    // The rows, value for value, and sequences that carry on past them.
    // A JSON null and an SQL NULL print alike in a row's text, so the json
    // columns are compared on their own as well.
    const json = `SELECT string_agg(coalesce(raw::text, 'SQL NULL') || ' / ' || coalesce(doc::text, 'SQL NULL'), ' | ' ORDER BY id) FROM public.plans`
    expect(await h.sqlIn('target', restored, json)).toBe(await h.sql('source', json))
    for (const table of ['plans', 'features']) {
      const rows = `SELECT string_agg(t::text, ' | ' ORDER BY id) FROM public.${table} t`
      expect(await h.sqlIn('target', restored, rows)).toBe(await h.sql('source', rows))
    }
    expect(await h.sqlIn('target', restored, `SELECT nextval(pg_get_serial_sequence('public.features', 'id'))`)).toBe('4')
    expect(await h.sqlIn('target', restored, `SELECT nextval(pg_get_serial_sequence('public.plans', 'id'))`)).toBe('3')
  }, 600_000)

  it('then finds no drift between the two', async () => {
    const r = await h.cli(['diff', '--target', 'restored', '--check', 'schema', '--json'], { cwd: ws })
    const scan = JSON.parse(r.stdout) as { checks: Array<{ check: string; issues: unknown[] }> }
    expect(scan.checks.flatMap(c => c.issues), r.stdout).toEqual([])
  }, 300_000)

  // --json is for scripts: stdout must parse whatever the outcome, and the exit
  // code must say what the text report would have.
  it('prints only JSON for a dry run', async () => {
    const r = await h.cli(['restore', '-e', 'restored', '--from-snapshot', 'latest', '--json'], { cwd: ws })
    expect(r.code, r.stderr).toBe(0)
    const preview = JSON.parse(r.stdout) as { dryRun: boolean; layers: Array<{ layer: string }> }
    expect(preview.dryRun).toBe(true)
    expect(preview.layers.map(l => l.layer)).toContain('schema')
  }, 120_000)

  it('refuses a non-empty target in JSON, and exits 1', async () => {
    const r = await h.cli(['restore', '-e', 'restored', '--from-snapshot', 'latest', '--apply', '--json'], { cwd: ws })
    expect(r.code).toBe(1)
    const refusal = JSON.parse(r.stdout) as { error: string; tables: string[] }
    expect(refusal.tables).toContain('orders')
  }, 120_000)

  // Snapshots taken before rows were captured as each column's text hold JSON
  // values instead; those still restore.
  it('restores rows a snapshot holds in the earlier format', async () => {
    const snapshots = join(ws, '.supaforge', 'snapshots')
    const [taken] = (await readdir(snapshots)).sort()
    const copy = '20980101T000000Z'
    await cp(join(snapshots, taken), join(snapshots, copy), { recursive: true })
    const manifestFile = join(snapshots, copy, 'manifest.json')
    await writeFile(manifestFile, JSON.stringify({ ...JSON.parse(await readFile(manifestFile, 'utf8')), timestamp: copy }))
    await writeFile(join(snapshots, copy, 'data', 'public.features.json'),
      JSON.stringify([{ id: 1, plan_id: 1, name: 'one' }, { id: 2, plan_id: 2, name: 'two' }]))
    await writeFile(join(snapshots, copy, 'data', 'public.plans.json'),
      JSON.stringify([{ id: 1, code: 'free', price: 0 }, { id: 2, code: 'pro', price: 1.5 }]))
    await h.createDatabase('target', 'sf_old_format')
    const r = await h.cli(['restore', '-e', 'old', '--from-snapshot', copy, '--apply'], { cwd: ws })
    expect(r.stdout + r.stderr).not.toMatch(/Rolled back/)
    expect(await h.sqlIn('target', 'sf_old_format', `SELECT string_agg(name, ',' ORDER BY id) FROM public.features`)).toBe('one,two')
  }, 300_000)

  // A restore that rolled back restored nothing, so it is not "incomplete":
  // it said both at once.
  it('reports a rolled-back restore as rolled back, not as incomplete', async () => {
    const snapshots = join(ws, '.supaforge', 'snapshots')
    const [taken] = (await readdir(snapshots)).sort()
    const copy = '20970101T000000Z'
    await cp(join(snapshots, taken), join(snapshots, copy), { recursive: true })
    const manifestFile = join(snapshots, copy, 'manifest.json')
    await writeFile(manifestFile, JSON.stringify({ ...JSON.parse(await readFile(manifestFile, 'utf8')), timestamp: copy }))
    const schemaFile = join(snapshots, copy, 'schema.sql')
    await writeFile(schemaFile, (await readFile(schemaFile, 'utf8')) + `
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
CREATE TABLE public.docs (id int PRIMARY KEY, embedding public.vector(3));
CREATE TABLE public.orders (id int);
`)
    await h.createDatabase('target', 'sf_rolled_back')
    const r = await h.cli(['restore', '-e', 'rolledback', '--from-snapshot', copy, '--apply', '--json'], { cwd: ws })
    expect(r.code).toBe(1)
    const result = JSON.parse(r.stdout) as { rolledBack?: unknown[]; incomplete?: boolean; errors: unknown[] }
    expect(result.errors.length).toBeGreaterThan(0)
    expect(result.rolledBack?.length).toBeGreaterThan(0)
    expect(result.incomplete).toBeUndefined()
  }, 300_000)

  // A snapshot needing an extension this server does not ship. Everything
  // that needs it used to roll the whole restore back with it.
  it('restores what it can without a missing extension, says what it left out, and exits 1', async () => {
    const snapshots = join(ws, '.supaforge', 'snapshots')
    const [taken] = await readdir(snapshots)
    const copy = '20990101T000000Z'
    await cp(join(snapshots, taken), join(snapshots, copy), { recursive: true })
    const manifestFile = join(snapshots, copy, 'manifest.json')
    const manifest = JSON.parse(await readFile(manifestFile, 'utf8')) as { timestamp: string }
    await writeFile(manifestFile, JSON.stringify({ ...manifest, timestamp: copy }))
    const schemaFile = join(snapshots, copy, 'schema.sql')
    await writeFile(schemaFile, (await readFile(schemaFile, 'utf8')) + `
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
CREATE TABLE public.docs (id int PRIMARY KEY, embedding public.vector(3));
CREATE INDEX docs_embedding ON public.docs (embedding);
`)
    await h.createDatabase('target', 'sf_partial')
    const r = await h.cli(['restore', '-e', 'partial', '--from-snapshot', copy, '--apply', '--json'], { cwd: ws })
    expect(r.code, r.stdout + r.stderr).toBe(1)
    const result = JSON.parse(r.stdout) as { incomplete: boolean; errors: unknown[]; skipped: Array<{ label: string; reason: string }> }
    expect(result.errors).toEqual([])
    expect(result.incomplete).toBe(true)
    expect(result.skipped.map(s => s.reason).join('\n')).toMatch(/lacks the vector extension/)
    expect(await h.sqlIn('target', 'sf_partial', `SELECT to_regclass('public.orders') IS NOT NULL`)).toBe('t')
    expect(await h.sqlIn('target', 'sf_partial', `SELECT to_regclass('public.docs') IS NULL`)).toBe('t')
  }, 300_000)
})
